### ISSUE TITLE
Database systems -- Research

### ISSUE THREAD

**Issue by sean-hale-dev** [sean-hale-dev/resume-org#4]
Look into the systems needed to be used in order to maintain efficient lookup speeds at scale for this database

- Look into things like MariaDB and MongoDB
- Look into efficient database searching technologies and structures

**Comment by varunravichandran22** [comment]
1. MongoDB :
MongoDB is a cross-platform document-oriented and a non relational (i.e., NoSQL) database program. It is an open-source document database, that stores the data in the form of key-value pairs. MongoDB is developed by MongoDB Inc. and initially released on 11 February 2009. It is written in C++, Go, JavaScript, Python languages. MongoDB offers high speed, high availability, and high scalability.

2. MariaDB :
MariaDB is an open source relational database management system (RDBMS) that is a compatible drop-in replacement for the widely used MySQL database technology. It is developed by MariaDB Foundation and initially released on 29 October 2009. MariaDB has a significantly high number of new features, which makes it better in terms of performance and user-orientation than MySQL.

**Comment by KolbyFlipper** [comment]
From my research, we should use MongoDB. One reason is that I believe team members are more experienced with Mongo, as it is taught extensively in Web Science, whereas MariaDB is used in web systems but only to a minor degree. Further, Mongo's Schema-less structure allows us to store employee skills in JSON, and store relevant information closer together, such as lists/arrays of employees with specific skills. Lastly, the way Mongo accesses data avoids using expensive joins operations, so it will likely be faster than an equivalent MariaDB instance.

I originally suggested we use GraphQL in conjunction with Mongo, but upon researching it further I no longer stand behind that; utilizing GraphQL would be a nonzero amount of work added, and the benefits of GraphQL are not very relevant to what we are doing. The client has said in today's meeting that on the high end, there will be 3000 resumes input into the system; queries should still be quite fast with that much data. If there were a million resumes, we should implement a knowledge graph, but that is not realistic for this application of our software. 

Additionally, GraphQL is an alternate API solution to REST, but we have already put into the requirements that we will provide a RESTful api, so it doesn't seem like we should arbitrarily change course to a less familiar solution for both us and the client.
